### PR TITLE
Change the snapshot way to do as it's deprecated

### PR DESCRIPTION
**Pull request by kpichardie**
Proc file isn't exists anymore. Need to use command to retrieve conntrack.

### CODE REVIEW

**Comment by frimik** [comment]
I followed it up with this 86cf726f869a0ea898bc794242ac04520f1bd2cb, let me know if you have any other info

**Comment by frimik** [comment]
guess changing the group of `conntrack` to an 'admin' group, adding the `dd-agent` user to that group and only allowing exec permissions on owner+group will tighten the command down further...

**Comment by kpichardie** [comment]
Thanks for the documentation addings. I think the capabilities is probably not the best way to manage this  because the problem is that someone unauthorized could flush conntrack table. So the best way in my view is to authorized sudo to dd-agent to use conntrack. WDYT ?

**Comment by frimik** [comment]
Yes, sudo is probably best.

I attempted to fix the cap_net_admin privs on the user level via the
pam_cap.so module, the user shell got the privileges, but it doesn't
automatically inherit to a binary the user executes. I think one would have
to do that with some native C wrapped code in python.

Anyway, it was a discovery in itself. Sudo is the better and more classical
approach.

Den fre 9 dec. 2016 11:23kpichardie <notifications@github.com> skrev:

**Pull request merged**
